In [36]:
import pandas as pd
import random
import numpy as np

# Create empty lists to store data
pet_types = []
age = []
size = []
gender = []
vaccination_status = []
spaying_status = []
medical_history = []
location = []
color = []
weight = []
special_characteristics = []
previous_owners = []
diet = []
training_level = []
suitability_for_living = []

# Define possible values for various features
sizes = ['Small', 'Medium', 'Large']
genders = ['Male', 'Female']
vaccination_statuses = ['Vaccinated', 'Not Vaccinated']
spaying_statuses = ['Spayed/Neutered', 'Not Spayed/Neutered']
medical_histories = ['Healthy', 'Minor Health Issues', 'Chronic Condition']
locations = ['Shelter', 'Rescue Organization']
colors = ['Brown', 'Black', 'White', 'Spotted', 'Mixed']
special_characteristic = ['Playful', 'Calm', 'Loyal', 'Affectionate', 'Active', 'Aggressive']
diets = ['Dry food', 'Canned food', 'Mixed diet']
training_levels = ['Basic', 'Advanced', 'None']
living_conditions = ['Apartment', 'Farm', 'Indoor', 'Outdoor', 'House']
pet_type_mapping = {
    'Dog': 0,
    'Cat': 1,
    'Rabbit': 2,
    'Turtle': 3,
    'Lizard': 4,
    'Chameleon': 5,
    'Crocodile': 6,
    'Frog': 7,
    'Gecko': 8,
    'Iguana': 9,
    'Salamander': 10,
    'Snake': 11,
    'Toad': 12,
    'Tortoise': 13
}

living_condition_mapping = {
    'Apartment': 0,
    'Farm': 1,
    'Indoor': 2,
    'Outdoor': 3,
    'House': 4
}

# List of pet types to filter
target_pet_types = ['Dog', 'Cat', 'Rabbit', 'Iguana']

# Generate random data for 300 rows
for _ in range(30000):
    pet_type = random.choice(list(pet_type_mapping.keys()))
    pet_types.append(pet_type_mapping[pet_type])
    age.append(random.randint(1, 20))
    size.append(random.choice(sizes))
    gender.append(random.choice(genders))
    vaccination_status.append(random.choice(vaccination_statuses))
    spaying_status.append(random.choice(spaying_statuses))
    
    if pet_type in target_pet_types:
       
        medical_history.append('Healthy')
    else:
    
       
        medical_history.append(random.choice(medical_histories))
    
    location.append(random.choice(locations))
    color.append(random.choice(colors))
    weight.append(random.randint(1, 20))
    special_characteristics.append(random.choice(special_characteristic))
    previous_owners.append(random.randint(1, 3))
    diet.append(random.choice(diets))
    training_level.append(random.choice(training_levels))
    suitability_for_living.append(random.choice(living_conditions))

# Create a DataFrame from the lists
data = {
    'Pet Type': pet_types,
    'Age': age,
    'Size': size,
    'Gender': gender,
    'Vaccination Status': vaccination_status,
    'Spaying/Neutering Status': spaying_status,
   
    'Medical History': medical_history,
    'Location': location,
    'Color': color,
    'Weight (kg)': weight,
    'Special Characteristics': special_characteristics,
    'Previous Owners': previous_owners,
    'Diet': diet,
    'Training Level': training_level,
    'Suitability for Living Condition': suitability_for_living
}

df = pd.DataFrame(data)

# Map categorical columns to integers
df['Size'] = df['Size'].map({'Small': 0, 'Medium': 1, 'Large': 2})
df['Gender'] = df['Gender'].map({'Male': 0, 'Female': 1})
df['Vaccination Status'] = df['Vaccination Status'].map({'Vaccinated': 0, 'Not Vaccinated': 1})
df['Spaying/Neutering Status'] = df['Spaying/Neutering Status'].map({'Spayed/Neutered': 0, 'Not Spayed/Neutered': 1})
df['Medical History'] = df['Medical History'].map({'Healthy': 0, 'Minor Health Issues': 1, 'Chronic Condition': 2})
df['Location'] = df['Location'].map({'Shelter': 0, 'Rescue Organization': 1})
df['Color'] = df['Color'].map({'Brown': 0, 'Black': 1, 'White': 2, 'Spotted': 3, 'Mixed': 4})
df['Special Characteristics'] = df['Special Characteristics'].map({'Playful': 0, 'Calm': 1, 'Loyal': 2, 'Affectionate': 3, 'Active': 4, 'Aggressive': 5})
df['Diet'] = df['Diet'].map({'Dry food': 0, 'Canned food': 1, 'Mixed diet': 2})
df['Training Level'] = df['Training Level'].map({'Basic': 0, 'Advanced': 1, 'None': 2})
df['Suitability for Living Condition'] = df['Suitability for Living Condition'].map(living_condition_mapping)
df.to_csv('dataset.csv', index=False)

df

,Pet Type,Age,Size,Gender,Vaccination Status,Spaying/Neutering Status,Medical History,Location,Color,Weight (kg),Special Characteristics,Previous Owners,Diet,Training Level,Suitability for Living Condition
0,6,3,0,1,1,0,1,0,2,14,4,3,0,0,4
1,0,5,0,1,0,0,0,1,2,17,2,1,0,0,2
2,6,9,0,1,1,1,1,1,0,15,2,1,0,0,4
3,12,16,2,1,0,0,1,0,1,7,5,3,0,1,3
4,5,11,1,0,1,1,0,0,3,1,3,1,2,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,8,20,0,1,0,0,1,1,2,13,1,2,2,1,3
29996,1,5,1,1,1,1,0,0,1,4,3,2,1,2,2
29997,0,12,2,1,0,1,0,1,3,15,4,1,1,1,1
29998,8,11,2,0,0,1,2,1,2,4,2,2,1,0,0
29999,2,10,1,0,1,1,0,0,2,11,1,2,2,1,4

In [37]:
df

,Pet Type,Age,Size,Gender,Vaccination Status,Spaying/Neutering Status,Medical History,Location,Color,Weight (kg),Special Characteristics,Previous Owners,Diet,Training Level,Suitability for Living Condition
0,6,3,0,1,1,0,1,0,2,14,4,3,0,0,4
1,0,5,0,1,0,0,0,1,2,17,2,1,0,0,2
2,6,9,0,1,1,1,1,1,0,15,2,1,0,0,4
3,12,16,2,1,0,0,1,0,1,7,5,3,0,1,3
4,5,11,1,0,1,1,0,0,3,1,3,1,2,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,8,20,0,1,0,0,1,1,2,13,1,2,2,1,3
29996,1,5,1,1,1,1,0,0,1,4,3,2,1,2,2
29997,0,12,2,1,0,1,0,1,3,15,4,1,1,1,1
29998,8,11,2,0,0,1,2,1,2,4,2,2,1,0,0
29999,2,10,1,0,1,1,0,0,2,11,1,2,2,1,4

In [56]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report
import joblib
# Load the dataset
df = pd.read_csv('dataset.csv')  # Replace with the path to your dataset

# Split the dataset into features (X) and the target (y)
X = df.drop(columns=['Suitability for Living Condition'])
y = df['Suitability for Living Condition']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and train a Decision Tree model
model = DecisionTreeClassifier()
model.fit(X_train, y_train)

# Create input data for prediction (replace these values with your own)
input_data = {
    'Pet Type':[1],
    'Age': [5],
    'Size': [1],  # Medium
    'Gender': [0],  # Male
    'Vaccination Status': [0],  # Vaccinated
    'Spaying/Neutering Status': [0],  # Spayed/Neutered
    'Medical History': [0],  # Healthy
    'Location': [0],  # Shelter
    'Color': [2],  # White
    'Weight (kg)': [10],
    'Special Characteristics': [0],  # Playful
    'Previous Owners': [1],
    'Diet': [0],  # Dry food
    'Training Level': [0]  # Basic
}

# Create a DataFrame for the input data
input_df = pd.DataFrame(input_data)

# Make predictions using the model
predicted_class = model.predict(input_df)

living_condition_mapping = {
    0: 'Apartment',
    1: 'Farm',
    2: 'Indoor',
    3: 'Outdoor',
    4: 'House'
}

# Get the predicted living condition label
predicted_condition_label = living_condition_mapping.get(predicted_class[0], 'Unknown')
model_filename = 'decision_tree_model.pkl'
joblib.dump(model, model_filename)
# Print the predicted living condition
print("Predicted Living Condition:", predicted_condition_label)

Predicted Living Condition: Outdoor